# Review (NP arrays)

Author: Justin Ventura

Date: Thursday, August 27th, 2020.

## - Description -

Just some review on how to use numpy arrays.

First we need to import numpy...

In [1]:
import numpy as np
print(np.__version__)

1.18.0


### Ex1: create an integer array with 10 random numbers (0-9), print it, then print it in reverse.

In [5]:
arr = np.random.randint(low=0, high=10, size=10, dtype='i')
print(arr, np.flip(arr), sep='\n')

[2 0 2 9 6 9 3 6 5 2]
[2 5 6 3 9 6 9 2 0 2]


### Ex2: create the array: [0,1,2,3,4,5,6,7,8,9] then print it as a 3x3 matrix.

In [7]:
arr = np.array([i for i in range(9)])
arr.shape = (3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Ex3: take the previous array, print its transpose, and flatten.

In [8]:
print(np.transpose(arr), arr.flatten(), sep='\n')

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[0 1 2 3 4 5 6 7 8]


### Ex4:

In [2]:
arr = [i for i in range(10)]
for i in range(10):
    print(f"arr[{i}] = {arr[i]}")

arr[0] = 0
arr[1] = 1
arr[2] = 2
arr[3] = 3
arr[4] = 4
arr[5] = 5
arr[6] = 6
arr[7] = 7
arr[8] = 8
arr[9] = 9
