# Linear Algebra

Author: Justin Ventura [[jventura3@gulls.salisbury.edu]]

Date: Thursday, September 29th, 2020.

## - Description -

Numpy for linear algebra!

In [8]:
# Libraries to use:
import numpy as np

In [9]:
# Numpy Linear Algebra
a = np.array([1, 3, 2])
b = np.array([0, 2, 2])

print(a*b) # mult_bcast

[0 6 4]


In [11]:
# Matrices:
a = np.array([[1,3,2]]) # Now a row vector
print(a)
print(np.transpose(a))

[[1 3 2]]
[[1]
 [3]
 [2]]
